repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/psf/black
    rev: 24.10.0 
    hooks:
      - id: black
        language_version: python3 
        stages: [pre-commit] 
 
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        stages: [pre-commit]
  
  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v1.12.0' 
    hooks:
        - id: mypy
          # always_run: true
  
  - repo: local
    hooks:
    - id: pytest
      name: pytest
      entry: ./venv/bin/pytest ./src
      language: system
      types: [python]
      pass_filenames: false
      always_run: true
  