repos:
  - repo: https://github.com/commitizen-tools/commitizen
    rev: v3.29.1
    hooks:
      - id: commitizen
        stages: [commit-msg]

  - repo: https://github.com/psf/black
    rev: 24.8.0 
    hooks:
      - id: black
        language_version: python3 
        stages: [pre-commit] 
 
  - repo: https://github.com/PyCQA/flake8
    rev: 7.1.1
    hooks:
      - id: flake8
        stages: [pre-commit]
  
  - repo: local
    hooks:
      - id: run-pytest
        name: run pytest
        entry: python -m pytest src 
        language: python  
        types: [python]
        additional_dependencies: [pytest]