# Generated by Django 5.1.4 on 2025-01-06 17:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies: list[tuple[str, str]] = []

    operations = [
        migrations.CreateModel(
            name="CustomerDBModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=100)),
                ("accepted_terms", models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name="WeekdayDBModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(
                        choices=[
                            ("monday", "monday"),
                            ("tuesday", "tuesday"),
                            ("wednesday", "wednesday"),
                            ("thursday", "thursday"),
                            ("friday", "friday"),
                            ("saturday", "saturday"),
                            ("sunday", "sunday"),
                        ],
                        max_length=100,
                        unique=True,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccountDBModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("email", models.CharField(max_length=255, unique=True)),
                ("password", models.CharField(max_length=255)),
                ("is_active", models.BooleanField()),
                (
                    "customer",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.customerdbmodel",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskDBModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                (
                    "type",
                    models.CharField(
                        choices=[("task", "task"), ("habit", "habit")], max_length=100
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.CharField(max_length=100)),
                ("datetime", models.DateTimeField()),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("career", "career"),
                            ("finance", "finance"),
                            ("study", "study"),
                            ("health", "health"),
                            ("leisure", "leisure"),
                            ("productivity", "productivity"),
                            ("miscellaneous", "miscellaneous"),
                        ],
                        max_length=100,
                    ),
                ),
                ("finally_datetime", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.customerdbmodel",
                    ),
                ),
                (
                    "weekday",
                    models.ManyToManyField(
                        related_name="task", to="models.weekdaydbmodel"
                    ),
                ),
            ],
        ),
    ]
