# Generated by Django 5.1.4 on 2025-01-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "create_weekdays_seed"),
    ]

    operations = [
        migrations.AlterField(
            model_name="taskdbmodel",
            name="finally_datetime",
            field=models.DateTimeField(null=True),
        ),
    ]
