# Generated by Django 5.1.4 on 2025-01-09 14:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("models", "0001_alter_taskdbmodel_finally_datetime"),
    ]

    operations = [
        migrations.CreateModel(
            name="SessionDBModel",
            fields=[
                ("id", models.UUIDField(primary_key=True, serialize=False)),
                ("created_at", models.DateTimeField()),
                ("expires_at", models.DateTimeField()),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="models.customerdbmodel",
                    ),
                ),
            ],
        ),
    ]
